on:
  push:
    branches:
      - deploy/prod
      - main

name: Build and Deploy a Container to Cloud Run
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: nestjs-prisma-nextjs
  REGION: asia-northeast1
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT }}/nestjs-prisma-nextjs:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t ${{ env.IMAGE }} api/ -f api/Dockerfile.production \
            --build-arg database_url=${{ secrets.DATABASE_URL }} \
            --build-arg shadow_database_url=${{ secrets.SHADOW_DATABASE_URL }} \
            --build-arg auth0_domain=${{ secrets.AUTH0_DOMAIN }} \
            --build-arg auth0_audience=${{ secrets.AUTH0_AUDIENCE }} \
            --build-arg auth0_issuer_url=${{ secrets.AUTH0_ISSUER_URL }} \
            --build-arg auth0_client_id=${{ secrets.AUTH0_CLIENT_ID }} \
            --build-arg stripe_secret_key=${{ secrets.STRIPE_SECRET_KEY }}
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --image ${{ env.IMAGE }} \
            --platform managed \
            --allow-unauthenticated

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
