on:
  push:
    branches:
      - deploy/prod

name: Build and Deploy a Container
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  SERVICE: nestjs-prisma-nextjs
  REGION: asia-northeast1
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT }}/nestjs-prisma-nextjs:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t ${{ env.IMAGE }} api/ -f api/Dockerfile.production
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --image ${{ env.IMAGE }} \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars "DATABASE_URL"="postgres://rffftuxjnpiogn:95bb35c65fd31bf821291450cb230f204cc7e67178cf449bfd07552a0a71d9b6@ec2-3-209-65-193.compute-1.amazonaws.com:5432/dagpf497bg9352"
            # --command "yarn && npx prisma generate && npx prisma migrate dev && yarn start:dev"

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}